# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- develop/staging-branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  projectsPath: '**/.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restoring packages'
  inputs:
    command: 'restore'
    projects: '$(projectsPath)'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: 'Building projects'
  inputs:
    command: 'build'
    projects: '$(projectsPath)'
- task: DotNetCoreCLI@2
  displayName: 'Running tests'
  inputs:
    command: 'test'
    projects: '**/*.Tests.csproj'